server:
  port: 6725
  #中文乱码
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: jdbc:mysql://${DS_HOST:localhost}:${DS_PORT:3306}/${DS_BASE:gaox}?characterEncoding=utf-8&useSSL=false&useUnicode=true}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启mybatis驼峰命名法
    map-underscore-to-camel-case: true
    # 配置扫描xml
    mapper-locations: classpath:/mybatis/**/*Mapper.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: net.gaox.bookmark.entity

dev: true