server:
  port: 6725
  #中文乱码
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gaox?characterEncoding=utf-8&useSSL=false&useUnicode=true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启mybatis驼峰命名法
    map-underscore-to-camel-case: true
    # 配置扫描xml
    mapper-locations: classpath:/mybatis/**/*Mapper.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: site.gaox.bookmark.entity

